name: docs

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: leanprover/lean-action@v1

      - run: lake exe cache get

      - run: lake build FormaleSystemeInLean:docs
        working-directory: docs

      - uses: actions/upload-pages-artifact@v3
        with:
          path: FormaleSystemeInLean/docs/.lake/build/doc

      - uses: actions/deploy-pages@v4